apiVersion: apps/v1
kind: Deployment
metadata:
  name: intial-deployment
spec:
   containers:
   - name: nginx
     image: nginx:alpine
    
        
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap-1
  namespace: default
data:
  index.html: |
    <html>
    <h1>Hello World!</h1>
    <p>This is version 1</p>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
   - port: 80
     targetPort: 80

